[package]
name = "TP1_Techno_Multimedia"
version = "0.1.0"
authors = ["traoremp <traoremp@vt.edu>"]

[dependencies]
lzw = { path = "../lzw" }
huffman_coding = { path = "../huffman-coding-rust" }
num_cpus = "*"
getopts = "0.2"
image = "*"
cpuprofiler = "0.0.2"